# .github/workflows/scrape.yml
name: Scrape INSEAD Knowledge

on:
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab


jobs:
  scrape_and_update_airtable:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a recent Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 pyairtable cloudscraper

    - name: Run scraper script
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }} # Access the secret here
      run: |
        python inseadknowledge.py
        # Optional: Upload logs as an artifact for debugging
        # uses: actions/upload-artifact@v4
        # with:
        #   name: scrape-logs
        #   path: insead_scrape.log
